INSERT INTO symptoms (slug,name_bn,body_part,sort_order) VALUES
 ('leaf-yellow','পাতা হলুদ হয়ে যাচ্ছে','leaf',1),
 ('leaf-brown-tip','পাতার আগা বাদামি ও শুকনো','leaf',2),
 ('leaf-white-powder','পাতায় সাদা গুঁড়ার মতো','leaf',3),
 ('leaf-black-spot','পাতায় কালো বা বাদামি দাগ','leaf',4),
 ('leaf-curl','পাতা কুঁকড়ে যাচ্ছে','leaf',5),
 ('leaf-holes','পাতায় ছিদ্র বা কাটা','leaf',6),
 ('leaf-sticky','পাতা আঠালো ও চিটচিটে','leaf',7),
 ('leaf-webbing','পাতার নিচে সূক্ষ্ম জাল','leaf',8),
 ('leaf-drop','পাতা ঝরে পড়ছে','leaf',9),
 ('leaf-pale','পাতা ফ্যাকাশে, শিরা সবুজ','leaf',10),
 ('stem-soft','কাণ্ড নরম ও পচা','stem',20),
 ('stem-white-cotton','কাণ্ডে সাদা তুলার মতো','stem',21),
 ('stem-black','কাণ্ডের গোড়া কালো','stem',22),
 ('stem-leggy','কাণ্ড লম্বা ও দুর্বল','stem',23),
 ('root-rot','শিকড় বাদামি, দুর্গন্ধ','root',30),
 ('root-bound','শিকড় টব ভরে গেছে','root',31),
 ('flower-bud-drop','কুঁড়ি ঝরে যাচ্ছে','flower',40),
 ('flower-none','ফুল আসছেই না','flower',41),
 ('flower-small','ফুল ছোট ও বিবর্ণ','flower',42),
 ('fruit-drop','ফল ঝরে যাচ্ছে','fruit',50),
 ('fruit-crack','ফল ফেটে যাচ্ছে','fruit',51),
 ('fruit-none','ফুল আসে কিন্তু ফল ধরে না','fruit',52),
 ('soil-mold','মাটির উপর সাদা ছত্রাক','soil',60),
 ('soil-gnats','মাটিতে ছোট মাছি','soil',61),
 ('soil-hard','মাটি শক্ত, পানি বসে থাকে','soil',62),
 ('soil-smell','মাটি থেকে দুর্গন্ধ','soil',63),
 ('whole-wilting','পুরো গাছ নেতিয়ে পড়েছে','whole',70),
 ('whole-slow','গাছ বাড়ছেই না','whole',71),
 ('whole-sunburn','রোদে পুড়ে গেছে','whole',72);
