-- 005_indexes.sql — FULLTEXT (retired)
--
-- MySQL 8's ngram parser could tokenise Bangla for real FULLTEXT search, but
-- MariaDB never shipped that parser, so this file was already a no-op there
-- and SearchService always ran its LIKE '%term%' fallback in practice. The
-- project decision (see SearchService.php) is to keep the LIKE path
-- permanently rather than depend on ngram/MariaDB version quirks — fine at
-- this content volume (60 plants / 40 problems / 20 guides). This file is
-- kept as an empty placeholder so the migration numbering/history stays
-- intact.
